# Generated by Django 4.1.4 on 2023-10-25 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliotego', '0002_venue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
