# Generated by Django 4.1.4 on 2023-10-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliotego', '0006_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='kotki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
