# Generated by Django 4.1.4 on 2023-10-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliotego', '0007_kotki'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kotki',
        ),
        migrations.AddField(
            model_name='venue',
            name='nazwa',
            field=models.CharField(default='', max_length=60),
        ),
    ]
