# Generated by Django 5.0 on 2023-12-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliotego', '0009_delete_venue_bibliotego_zdjęcie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, db_column='ISBN', max_length=255, null=True)),
                ('book_title', models.CharField(blank=True, db_column='Book-Title', max_length=255, null=True)),
                ('book_author', models.CharField(blank=True, db_column='Book-Author', max_length=255, null=True)),
                ('year_of_publication', models.IntegerField(blank=True, db_column='Year-Of-Publication', null=True)),
                ('publisher', models.CharField(blank=True, db_column='Publisher', max_length=255, null=True)),
                ('image_url_s', models.CharField(blank=True, db_column='Image-URL-S', max_length=255, null=True)),
                ('image_url_m', models.CharField(blank=True, db_column='Image-URL-M', max_length=255, null=True)),
                ('image_url_l', models.CharField(blank=True, db_column='Image-URL-L', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Książka',
                'verbose_name_plural': 'Książki',
                'db_table': 'books',
            },
        ),
        migrations.AlterModelOptions(
            name='bibliotego',
            options={'verbose_name': 'Książka', 'verbose_name_plural': 'Książki'},
        ),
    ]
