# Generated by Django 5.0 on 2023-12-30 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliotego', '0010_books_alter_bibliotego_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibliotego',
            options={'verbose_name': 'Książka1', 'verbose_name_plural': 'Książki1'},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Książka2', 'verbose_name_plural': 'Książki2'},
        ),
        migrations.AddField(
            model_name='books',
            name='gatunki',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bibliotego.gatunki'),
        ),
    ]
